main:
  blockcreative: true
perm:
  mine: 'mte.miningmoney'
msg:
  QUARTZ_ORE: '&2MineToEarn &8» &e+200 coins &f(Quartz ore broken)'
  EMERALD_ORE: '&2MineToEarn &8» &e+150 coins &f(Emerald ore broken)'
  DIAMOND_ORE: '&2MineToEarn &8» &e+120 coins &f(Diamond ore broken)'
  REDSTONE_ORE: '&2MineToEarn &8» &e+100 coins &f(Redstone ore broken)'
  GOLD_ORE: '&2MineToEarn &8» &e+80 coins &f(Gold ore broken)'
  IRON_ORE: '&2MineToEarn &8» &e+50 coins &f(Iron ore broken)'
  COAL_ORE: '&2MineToEarn &8» &e+30 coins &f(Coal ore broken)'
  LAPIS_ORE: '&2MineToEarn &8» &e+10 coins &f(Lapis ore broken)'
pay:
  QUARTZ_ORE: 200
  EMERALD_ORE: 150
  DIAMOND_ORE: 120
  REDSTONE_ORE: 100
  GOLD_ORE: 80
  IRON_ORE: 50
  COAL_ORE: 30
  LAPIS_ORE: 10